; PlatformIO Project Configuration File
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.flash_size = 4M
monitor_speed = 115200
lib_deps = 
    ESP8266WebServer
    ESP8266WiFi
    EEPROM
